USE [CRUD App];
GO
CREATE TABLE dbo.PRODUCTS (
  PRODUCTID INT IDENTITY(1,1) PRIMARY KEY,
  PRODUCTNAME NVARCHAR(100) NOT NULL,
  PRICE DECIMAL(10,2) NOT NULL,
  STOCK INT NOT NULL
);


INSERT INTO PRODUCTS (PRODUCTNAME, PRICE, STOCK)
VALUES
 ('Sample A', 9.99, 10),
 ('Sample B', 19.50, 5);